FloridoERP/Controllers/PaymentsMethods/PaymentsMethodsController.cs
using App.BLL.Lookups;
using App.BLL.PaymentMethod;
using App.Common;
using App.Entities.ViewModels.PaymentMethod;
using FloridoERP.ViewModels.Lookups;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloridoERP.Controllers.PaymentsMethods
{
    public class PaymentsMethodsController : Controller
    {
        private SatPaymentMethodCodeBusiness _SatPaymentMethodCodeBusiness;
        private PaymentsMethodsBusiness _PaymentsMethodsBusiness;

        public PaymentsMethodsController()
        {
            _SatPaymentMethodCodeBusiness = new SatPaymentMethodCodeBusiness();
            _PaymentsMethodsBusiness = new PaymentsMethodsBusiness();
        }

        // GET: PaymentMethods
        public ActionResult PAME001()
        {
            FillLookups();
            var Model = new PaymentMethodModel();
            return View(Model);
        }

        [HttpPost]
        public ActionResult PAME001 (PaymentMethodModel Model)
        {
            if(Session["User"] != null)
            {
                if (_PaymentsMethodsBusiness.AddPaymentMethod(Model))
                    return Json(new { success = true, Json = Model, responseText = "registro exitoso" }, JsonRequestBehavior.AllowGet);
            }
            return View(Model);
        }

        public ActionResult PAME002()
        {
            var Model = new PaymentMethodModel();
            Model.PaymentsMethods = _PaymentsMethodsBusiness.GetPaymentMethods();
            return View(Model);
        }

        [HttpPost]
        public ActionResult ActionDisablePaymentMethod(int PaymentMethodId)
        {
            if (_PaymentsMethodsBusiness.DisablePaymentMethod(PaymentMethodId))
                return Json(new { success = true, Json = PaymentMethodId, responseText = "Método desactivado" }, JsonRequestBehavior.AllowGet);

            return Json(new { success = false, responseText = "Ocurrió un error, contacte a sistemas!" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionEditPaymentMethod(int PaymentMethodId)
        {
            var PaymentMethod = new PaymentMethodModel();
            PaymentMethod = _PaymentsMethodsBusiness.GetPaymentMethodById(PaymentMethodId);
            FillLookups();
            ModelState.Clear();
            return PartialView("_PAME002", PaymentMethod);
        }

        [HttpPost]
        public ActionResult ActionEditPaymentMethod(PaymentMethodModel Model)
        {
            if (_PaymentsMethodsBusiness.UpdatePaymentMethod(Model))
                return Json(new { success = true, Json = Model, responseText = "Método de pago editado" }, JsonRequestBehavior.AllowGet);

            return PartialView("_PAME002", Model);
        }

        void FillLookups()
        {
            var Bla = new Lookups();
            ViewBag.SatCode = new SelectList(_SatPaymentMethodCodeBusiness.SatPaymentMethodCodeList(), "sat_pm_code", "sat_pm_description");
            ViewBag.Currency = Bla.Currencies();
            ViewBag.TypeV = Bla.VoucherType();
        }
    }
}

FloridoERP/Views/PaymentsMethods/PAME002.cshtml
@model App.Entities.ViewModels.PaymentMethod.PaymentMethodModel

@{
    ViewBag.Title = "PAME002";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    table {
        width: 100%;
        margin: 20px 0;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid #cdcdcd;
    }

        table th, table td {
            padding: 5px;
            text-align: left;
        }

        td.details-control:before {
            display: inline-block;
            font: normal normal normal 14px/1 FontAwesome;
            font-size: inherit;
            text-rendering: auto;
            -webkit-font-smoothing: antialiased;
            content: "\f101";
            cursor: pointer;
        }

    tr.details td.details-control:before {
        display: inline-block;
        font: normal normal normal 14px/1 FontAwesome;
        font-size: inherit;
        text-rendering: auto;
        -webkit-font-smoothing: antialiased;
        content: "\f103";
        cursor: pointer;
    }

    input[type="number"]::-webkit-outer-spin-button, input[type="number"]::-webkit-inner-spin-button {
        -webkit-appearance: none !important;
        margin: 0;
    }

    input[type="number"] {
        -moz-appearance: textfield !important;
    }
</style>
@Styles.Render("~/bundles/datepicker/css")
@Styles.Render("~/bundles/datatables/css")

@*Breadcrumb*@
<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("CTMS000","Customers")">Caja</a></li>
                    <li><a href="@Url.Action("CTMS001","Customers")">Catálogos</a></li>
                    <li class="active">
                        <span>Métodos de Pago</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Métodos de Pago
            </h2>
            <small>Editar métodos de pago</small>
        </div>
    </div>
</div>

<div class="content animated-panel" id="TableSection">
    <div class="hpanel">
        <div class="panel-body">
            <div class="table-responsive m-t">
                <table id="PaymentsMethodsTable" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Orden</th>
                            <th>Activo</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PaymentsMethods)
                        {
                            <tr>
                                <td>@item.pm_id</td>
                                <td>@item.pm_name</td>
                                <td>@item.pm_order</td>
                                @if (item.pm_menu)
                                {
                                    <td><div checked><div class="icheckbox_square-green checked disabled" style="position: relative;"><input type="checkbox" disabled="" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div></div></td>
                                }
                                else
                                {
                                    <td><div checked><div class="icheckbox_square-green  disabled" style="position: relative;"><input type="checkbox" disabled="" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div></div></td>
                                }
                                <td id="@item.pm_id"></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@*Div to display modal*@
<div id="PM">
</div>
@section Scripts{
    @Scripts.Render("~/bundles/datatables/js")
    @Scripts.Render("~/bundles/datatablesBootstrap/js")
    <script src="~/Vendor/iCheck/icheck.min.js"></script>
    <script type="text/javascript">
        var table = $('#PaymentsMethodsTable').DataTable({
            oLanguage: {
                "sProcessing": "Procesando...", "sLengthMenu": "Mostrar _MENU_ registros", "sZeroRecords": "No se encontraron resultados", "sEmptyTable": "Ningún dato disponible en esta tabla", "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros", "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros", "sInfoFiltered": "(filtrado de un total de _MAX_ registros)", "sInfoPostFix": "", "sSearch": "Buscar:", "sUrl": "", "sInfoThousands": ",", "sLoadingRecords": "Cargando...", "oPaginate": { "sFirst": "Primero", "sLast": "Último", "sNext": "Siguiente", "sPrevious": "Anterior" }, "oAria": { "sSortAscending": ": Activar para ordenar la columna de manera ascendente", "sSortDescending": ": Activar para ordenar la columna de manera descendente" }
            },
            dom: "<'row'<'col-sm-4'l><'col-sm-4 text-left'B><'col-sm-4'f>t<'col-sm-6'i><'col-sm-6'p>>",
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "Todos"]],
            columns: [
                { data: 'pm_id' },
                { data: 'pm_name' },
                { data: 'pm_order' },
                { data: 'pm_menu' },
            ],

            columnDefs: [
                {
                    className: 'text-center'
                },
                { orderable: false, targets: [0, 4] },
                { visible: false, targets: [0] },
                {
                    data: null,
                    width: "30%",
                    targets: 4,
                    defaultContent: '<button id="EditPM" class="btn btn-xs btn-outline btn-info EditPM">Editar</button> <button id="DisablePM" class="btn btn-xs btn-outline btn-danger DisablePM">Desactivar</button>'
                }]
        });

        $('#TableSection tbody').on('click', 'tr button.DisablePM', function () {
            var td = $(this).closest('td');
            var pmId = td.context.parentNode.id;

            swal({
                title: "¿Estas seguro?",
                text: "Una vez que se desactive no aparecerá en el punto de venta",//"Una vez que se desactive no aparecerán los productos relacionados a esta compañía en el punto de venta",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Sí",
                cancelButtonText: "No",
                closeOnConfirm: true,
                closeOnCancel: false
            },
            function (isConfirm) {
                if (isConfirm) {
                    StartLoading();
                    $.post({
                        url: '@Url.Action("ActionDisablePaymentMethod", "PaymentsMethods")',
                        Type: 'POST',
                        dataType: 'json',
                        data: { "PaymentMethodId": pmId },
                        success: function (data) {
                            EndLoading();
                            if (data.success) {
                                swal({
                                    title: 'Método de Pago',
                                    text: "Método Desactivado",
                                    type: "success"
                                }, function () { window.location.reload(true); });
                            }
                            else {
                                swal("Error", "Ocurrió un error, contacte a sistemas", "error");
                            }
                        }
                    });
                } else {
                    swal("Error", "Compañía no desactivada", "error");
                }
            })
        });

        $("#TableSection tbody").on('click', 'tr button.EditPM', function () {
            var td = $(this).closest('td');
            var paymentMethodId = td.context.parentNode.id;

            $.ajax({
                url: '@Url.Action("ActionEditPaymentMethod", "PaymentsMethods")',
                Type: 'GET',
                data: { "PaymentMethodId": paymentMethodId },
                success: function (data) {
                    $("#PM").html(data);
                    $("#PaymentMethodModal").modal('show');
                }
            });
        });

        function EditPaymentMethod() {
            StartLoading();
            $.post({
                url: '@Url.Action("ActionEditPaymentMethod", "PaymentsMethods")',
                dataType: 'json',
                Type: 'POST',
                data: $("#formEditPaymentMethod").serialize(),
                success: function (data) {
                    var text = data.responseText;
                    $('#PaymentMethodModal').modal('hide');
                    EndLoading();
                    swal({
                        title: 'Método de pago',
                        text: text + " exitosamente.",
                        type: "success"
                    }, function () { window.location.reload(true); });
                },
            });
        }


    </script>
}

FloridoERP/Views/PaymentsMethods/_PAME002.cshtml
@model App.Entities.ViewModels.PaymentMethod.PaymentMethodModel

<div class="modal fade" id="PaymentMethodModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                <h4 id="ModalTitle" class="modal-title">Editar Método de Pago</h4>
                <small id="ModalDescription" class="font-bold">Formulario para editar un método de pago.</small>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("ActionEditPaymentMethod", "PaymentsMethods", FormMethod.Post, new { name = "formEditPaymentMethod", id = "formEditPaymentMethod" }))
                {
                    @Html.HiddenFor(model => model.Id)
                    <div class="row">
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.MenuOrder, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.EditorFor(model => model.MenuOrder, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MenuOrder, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.Menu, htmlAttributes: new { @class = "control-label" })
                            <br />
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(m => m.Menu)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.SatCode, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.DropDownListFor(model => model.SatCode, null, "-- Selecciona relación con SAT--", htmlAttributes: new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(model => model.SatCode, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.Currency, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.DropDownListFor(model => model.Currency, null, htmlAttributes: new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(model => model.Currency, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.TypeV, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.DropDownListFor(model => model.TypeV, null, htmlAttributes: new { @class = "form-control select2" })
                                @Html.ValidationMessageFor(model => model.TypeV, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.MaxAllowedPerSale, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.EditorFor(model => model.MaxAllowedPerSale, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MaxAllowedPerSale, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.MaxChangedAllowedPerSale, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.EditorFor(model => model.MaxChangedAllowedPerSale, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MaxChangedAllowedPerSale, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.MaxAllowedCashBack, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.EditorFor(model => model.MaxAllowedCashBack, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MaxAllowedCashBack, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.AllowExcededBalance, htmlAttributes: new { @class = "control-label" })
                            <br />
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(m => m.AllowExcededBalance)
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.CanReturnChange, htmlAttributes: new { @class = "control-label" })
                            <br />
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(m => m.CanReturnChange)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.CancellationOrder, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.EditorFor(model => model.CancellationOrder, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CancellationOrder, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.AcceptWithdraw, htmlAttributes: new { @class = "control-label" })
                            <br />
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(m => m.AcceptWithdraw)
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.AcceptDonation, htmlAttributes: new { @class = "control-label" })
                            <br />
                            <div class="col-md-8">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(m => m.AcceptDonation)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12" style="">
                            <div class="form-group col-lg-12">
                                <div class="text-right">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                    <button type="button" class="btn btn-success" id="SavePM" onclick="EditPaymentMethod()">Guardar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<div id="ajaxTarget">
    <script type="text/javascript">
        $(function () {
            $('input').iCheck({ checkboxClass: 'icheckbox_square-green', });

            $("#formEditPaymentMethod").validate({
                errorClass: 'help-block animation-slideDown', // You can change the animation class for a different entrance animation - check animations page
                errorElement: "span",
                errorPlacement: function (error, element) {
                    $(element)
                        .closest("form")
                        .find("span[data-valmsg-for='" + element.attr("id") + "']")
                        .append(error);
                },
                highlight: function (e) {
                    $("#AddPaymentMethod").attr("disabled", "disabled");
                    $(e).closest('.form-group').removeClass('has-success has-error').addClass('has-error');
                    $(e).closest('.help-block').remove();
                },
                success: function (e) {
                    $("#AddPaymentMethod").removeAttr("disabled");
                    e.closest('.form-group').removeClass('has-success has-error');
                    e.closest('.help-block').remove();
                },
                rules: {
                    Name: {
                        required: true
                    },
                    Key: {
                        digits: true
                    },
                    MenuOrder: {
                        digits: true
                    },
                    MaxAllowedPerSale: {
                        number: true
                    },
                    MaxChangedAllowedPerSale: {
                        number: true
                    },
                    MaxAllowedCashBack: {
                        number: true
                    },
                    CancellationOrder: {
                        digits: true
                    }
                },
                messages: {
                    Name: {
                        required: function () { return "Nombre de pago requerido."; }
                    },
                    Key: {
                        digits: function () { return "Solo admite números."; }
                    },
                    MenuOrder: {
                        digits: function () { return "Solo admite números."; }
                    },
                    MaxAllowedPerSale: {
                        number: function () { return "Solo admite números enteros o decimales."; }
                    },
                    MaxChangedAllowedPerSale: {
                        number: function () { return "Solo admite números enteros o decimales."; }
                    },
                    MaxAllowedCashBack: {
                        number: function () { return "Solo admite números enteros o decimales."; }
                    },
                    CancellationOrder: {
                        digits: function () { return "Solo admite números."; }
                    }
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });
    </script>
</div>