FloridoERP/Controllers/Inventory/InventoryCalendarController.cs
using App.BLL.Inventory;
using App.Entities.ViewModels.Inventory;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace FloridoERP.Controllers.Inventory
{
    public class InventoryCalendarController : Controller
    {
        private readonly InventoryCalendarBusiness _InventoryCalendarBussines;

        public InventoryCalendarController()
        {
            _InventoryCalendarBussines = new InventoryCalendarBusiness();
        }

        [HttpGet]
        public ActionResult ActionMonthCalendar(DateTime DateStart)
        {
            var lastDayOfMonth = DateStart.AddMonths(2).AddDays(-1);
            DateStart = DateStart.AddMonths(-1);
            var Inventorys = _InventoryCalendarBussines.getInventoryCalendarDatesBetween(DateStart, lastDayOfMonth);
            return Json(Inventorys, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ActionUpdateInventoryCalendarOnlyDate(InventoryCalendarModel InventoryObj)
        {
            if (HttpContext.User.Identity.Name != null)
            {
                var updateReturn = _InventoryCalendarBussines.UpdateInventoryCalendarOnlyDate(InventoryObj, HttpContext.User.Identity.Name, InventoryObj.program_id);
                if (updateReturn)
                    return new JsonResult() { Data = new { success = true }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
                else
                    return Json(new { success = false, responseText = "Error al registrar!" }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { success = false, responseText = "Termino tu sesión." }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ActionInventoryCalendar(InventoryCalendarModel InventoryObj, bool typeOf)
        {
            if (HttpContext.User.Identity.Name != null)
            {
                bool updateReturn;
                if (typeOf)//true inserta
                {
                    InventoryObj.cuser = HttpContext.User.Identity.Name;
                    updateReturn = _InventoryCalendarBussines.InsertInventoryCalendar(InventoryObj);
                }
                else//false hace update
                {
                    InventoryObj.uuser = HttpContext.User.Identity.Name;
                    updateReturn = _InventoryCalendarBussines.UpdateInventoryCalendar(InventoryObj);
                }
                if (updateReturn)
                {
                    var lastDayOfMonth = InventoryObj.start.AddMonths(2).AddDays(-1);
                    InventoryObj.start = InventoryObj.start.AddMonths(-1);
                    var Inventorys = _InventoryCalendarBussines.getInventoryCalendarDatesBetween(InventoryObj.start, lastDayOfMonth);

                    return new JsonResult() { Data = new { success = true, Inventorys, responseText = "Registro Exitoso!" }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
                }
                else
                    return Json(new { success = false, responseText = "Error al registrar!" }, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(new { success = false, responseText = "Termino tu sesión." }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ActionAddInventoryCyclic(InventoryCalendarModel Inventory, List<string> part_numbers)
        {
            if (HttpContext.User.Identity.Name != null)
                return new JsonResult() { Data = new { success = true, Inventory = _InventoryCalendarBussines.AddInventoryCyclic(Inventory, part_numbers, HttpContext.User.Identity.Name), responseText = "Registro Exitoso!" }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
            else
                return Json(new { success = false, responseText = "SF" }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult ActionCloseInventory(int id, DateTime start)
        {
            if (HttpContext.User.Identity.Name != null)
            {
                var r = _InventoryCalendarBussines.CancelInventory(id, HttpContext.User.Identity.Name);
                if (r)
                {
                    var lastDayOfMonth = start.AddMonths(2).AddDays(-1);
                    start = start.AddMonths(-1);
                    var Inventorys = _InventoryCalendarBussines.getInventoryCalendarDatesBetween(start, lastDayOfMonth);
                    return new JsonResult() { Data = new { success = r, Inventories = Inventorys}, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
                }
                else
                {
                    return new JsonResult() { Data = new { success = r }, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
                }
            }             
            else
                return Json(new { success = false, responseText = "SF" }, JsonRequestBehavior.AllowGet);
        }
    }
}

FloridoERP/Controllers/Inventory/InventoryController.cs
using App.BLL.CommonBusiness;
using App.BLL.Inventory;
using App.BLL.MaCode;
using App.BLL.Site;
using App.Entities.ViewModels.Inventory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloridoERP.Controllers.Inventory
{
    public class InventoryController : Controller
    {
        private readonly SysMaClassBusiness _MaClassBussines;
        private readonly MaCodeBusiness _MaCodeBusiness;
        private readonly InventoryCalendarBusiness _InventoryCalendarBussines;
        private readonly SiteBusiness _siteBusiness;
        private readonly InventoryTypeBusiness _InventoryTypeBusiness;

        // GET: Inventory
        public InventoryController()
        {
            _MaClassBussines = new SysMaClassBusiness();
            _MaCodeBusiness = new MaCodeBusiness();
            _InventoryCalendarBussines = new InventoryCalendarBusiness();
            _siteBusiness = new SiteBusiness();
            _InventoryTypeBusiness = new InventoryTypeBusiness();
        }

        public ActionResult INVE000()
        {
            return View();
        }

        public ActionResult INVE001()
        {
            var Date = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            var startDate = Date.AddMonths(-1);
            var endDate = Date.AddMonths(2).AddDays(-1);
            InventoryCalendarModel model = new InventoryCalendarModel
            {
                siteList = _siteBusiness.GetAllSitesName(),
                InventoryTypeList = _InventoryTypeBusiness.GetAllInventoryTypeActives(),
                InventoryCalendarModellist = _InventoryCalendarBussines.getInventoryCalendarDatesBetween(startDate, endDate)
            };
            return View(model);
        }

        public ActionResult INVE002()
        {
            var Options = new InventoryTypeOptionModel
            {
                ListMaClass = _MaClassBussines.GetMaClassDivisionForLevel(1),
                ListMaCode = _MaCodeBusiness.GetListByCode("TYPE_REVIEW"),
                ListInventory = _InventoryTypeBusiness.GetAllInventoryType()
            };
            return View(Options);
        }

        public ActionResult INVE003()
        {
            InventoryCalendarModel model = new InventoryCalendarModel
            {
                siteList = _siteBusiness.GetAllSitesName()
            };
            return View(model);
        }

        public ActionResult MENWSM000()
        {
            return View(_siteBusiness.GetAllSitesName());
        }
    }
}

FloridoERP/Controllers/Inventory/InventoryTypeController.cs
using App.BLL.Inventory;
using App.Entities.ViewModels.Inventory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloridoERP.Controllers.Inventory
{
    public class InventoryTypeController : Controller
    {
        private readonly InventoryTypeBusiness _InventoryTypeBusiness;

        public InventoryTypeController()
        {
            _InventoryTypeBusiness = new InventoryTypeBusiness();
        }

        [HttpPost]
        public ActionResult ActionSaveInventoryType(InventoryTypeModel InventoryType, List<InventoryTypeDetailsModel> InventoryTypeDetails)
        {
            if (Session["User"] != null)
                return new JsonResult() { Data = _InventoryTypeBusiness.SaveInventory(InventoryType, InventoryTypeDetails, Session["User"].ToString()), JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
            else
                return new JsonResult() { Data = "SF", JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
        }

        [HttpPost]
        public ActionResult ActionEditInventoryType(InventoryTypeModel InventoryType, List<InventoryTypeDetailsModel> InventoryTypeDetails)
        {
            if (Session["User"] != null)
                return new JsonResult() { Data = _InventoryTypeBusiness.EditInventory(InventoryType, InventoryTypeDetails, Session["User"].ToString()), JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
            else
                return Json("SF", JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionGetAllInventoryType()
        {
            if (Session["User"] != null)
                return new JsonResult() { Data = _InventoryTypeBusiness.GetAllInventoryType(), JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };

            return Json("SF", JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionGetInventoryTypeDatails(int IdInventoryType)
        {
            if (Session["User"] != null)
                return new JsonResult() { Data = _InventoryTypeBusiness.GetInventoryTypeDatails(IdInventoryType), JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };

            return Json("SF", JsonRequestBehavior.AllowGet);
        }

        public ActionResult ActionIsActiveInventory(int Inventory, bool Active)
        {
            if (Session["User"] != null)
                return new JsonResult() { Data = _InventoryTypeBusiness.IsActiveInventory(Inventory, Active, Session["User"].ToString()), JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };

            return Json("SF", JsonRequestBehavior.AllowGet);
        }
    }
}

FloridoERP/Views/Inventory/INVE000.cshtml
@{ ViewBag.Title = "INVE000"; }

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="MENWSM000">Almacen</a></li>
                    <li class="active">
                        <span>Almacen</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Inventario
            </h2>
            <small>Menu de Inventario. </small>
        </div>
    </div>
</div>

<div class="content animate-panel">
    <div class="row">

        <div class="col-md-4">
            <div class="hpanel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="INVE002">
                            <h2 class="m-b-xs">Tipo de inventarios</h2>
                            <div class="m">
                                <i class="fa fa-file-text-o fa-5x"></i>
                            </div>
                            <p class="small">
                                Se agregan los tipos de inventarios
                            </p>
                            <br />
                        </a>
                        <a href="INVE002" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="hpanel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="INVE001">
                            <h2 class="m-b-xs">Calendario</h2>
                            <div class="m">
                                <i class="fa fa-calendar fa-5x"></i>
                            </div>
                            <p class="small">
                                Se crean fechas programados de inventarios.
                            </p>
                            <br />
                        </a>
                        <a href="INVE001" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

FloridoERP/Views/Inventory/INVE001.cshtml
@model App.Entities.ViewModels.Inventory.InventoryCalendarModel
@{
    ViewBag.Title = "INVE001";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> Sites = new List<SelectListItem>();
    Sites.Add(new SelectListItem { Text = "Seleccione una opción", Value = "" });
    if (Model.siteList != null)
    {
        foreach (var item in Model.siteList)
        {
            Sites.Add(new SelectListItem { Text = item.SiteName, Value = item.SiteCode });
        }
    }
    Sites.Add(new SelectListItem { Text = "TODAS LAS TIENDAS", Value = "0000" });
    List<SelectListItem> Types = new List<SelectListItem>();
    Types.Add(new SelectListItem { Text = "Seleccione una opción", Value = "" });
    if (Model.InventoryTypeList != null)
    {
        foreach (var item in Model.InventoryTypeList)
        {
            Types.Add(new SelectListItem { Text = item.InventoryName, Value = item.IdInventoryType.ToString() });
        }
    }
}

@section Styles {
    @Styles.Render("~/bundles/metisMenu/css")
    @Styles.Render("~/bundles/animate/css")
    @Styles.Render("~/bundles/fullcalendar/css")
    @Styles.RenderFormat(BundlesFormats.Print, "~/bundles/fullcalendar-media/css")
    @Styles.Render("~/bundles/peicon7stroke/css")
    @Styles.Render("~/bundles/style/css")
    @Styles.Render("~/bundles/bootstrap-tour/css")
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="MENWSM000">Almacen</a></li>
                    <li><a href="INVE000">Inventario</a></li>
                    <li class="active">
                        <span id="MenuLeftAction">Calendarizar Inventarios</span>
                    </li>
                    <li>
                        <a>
                            <h5 class="pe-7s-help1 text-info" data-toggle="tooltip" data-placement="left" data-original-title="Ayuda" onclick="HelpTour();"></h5>
                        </a>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Calendarizar Inventarios
            </h2>
            <small>Asignar fecha a inventarios</small>
        </div>
    </div>
</div>
<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel hblue">
                <div class="panel-heading hbuilt">
                    <div class="panel-tools">
                        <a id="showhideCalendar" class="showhide"><i class="fa fa-chevron-up"></i></a>
                    </div>
                    <a onclick="showhideCalendar.click();">Calendario de inventarios</a>
                </div>
                <div id="CalendarPanel" class="panel-body">
                    <div id="calendar"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ModalAddInventory" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                <h4 id="ModalTitle" class="modal-title">Agregar Pagina</h4>
                <small id="ModalDescription" class="font-bold">Formulario para registrar una nueva pagina.</small>
            </div>
            @using (Html.BeginForm("ActionInsertInventoryCalendar", "InventoryCalendar", FormMethod.Post, new { name = "form", id = "form" }))
            {
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-lg-6">
                            <input type="hidden" id="idInventory" value="">
                            <input type="hidden" id="idInventoryDate" value="">
                            <label for="page_id" title="ID Pagina." data-toggle="tooltip" data-placement="right">Nombre</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-align-left"></span>
                                </span>
                                @Html.TextBoxFor((x => x.title), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label for="page_name" title="Nombre de la página." data-toggle="tooltip" data-placement="right">Descripción</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-align-justify"></span>
                                </span>
                                @Html.TextBoxFor((x => x.description), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label title="URL de la página" data-toggle="tooltip" data-placement="right">Tienda</label>
                            @Html.DropDownList("SiteValue", Sites, new { @class = "form-control drop" })
                        </div>
                        <div class="form-group col-lg-6">
                            <label title="URL de la página" data-toggle="tooltip" data-placement="right">Tipo de inventario</label>
                            @Html.DropDownList("TypeValue", Types, new { @class = "form-control drop" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-sign-out"></i> Salir</button>
                    <button id="btnCancel" type="button" class="btn btn-danger fa fa-close" onclick="CancelInventory();"> Cancelar </button>
                    <button id="btExec" type="button" class="btn btn-success fa fa-save" onclick="InsertInventory();"> Registrar</button>
                </div>
            }
        </div>
    </div>
</div>

@Html.Hidden("Inventorys", Json.Encode(Model.InventoryCalendarModellist))
@Html.Hidden("InventorysTypesJS", Json.Encode(Model.InventoryTypeList))
@section Scripts {
    @Scripts.Render("~/bundles/slimscroll/js")
    @Scripts.Render("~/bundles/fullcalendar/js")
    @Scripts.Render("~/bundles/bootstrap-tour/js")
    @Scripts.Render("~/bundles/INVE001/js")
}

FloridoERP/Views/Inventory/MENWSM000.cshtml
@{ ViewBag.Title = "MENWSM000"; }

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="MENWSM000">Almacen</a></li>
                    <li class="active">
                        <span>Almacen</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Almacen
            </h2>
            <small>Menu de Almacen. </small>
        </div>
    </div>
</div>

<div class="content animate-panel">
    <div class="row">
        <div class="col-md-4">
            <div class="hpanel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="INVE000">
                            <h2 class="m-b-xs">Inventario</h2>
                            <div class="m">
                                <i class="fa fa-bar-chart fa-5x"></i>
                            </div>
                            <p class="small">
                                Menu de inventario
                            </p>
                            <br />
                        </a>
                        <a href="INVE000" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>