FloridoERP/Controllers/Donations/DonationsController.cs
using System.Web.Mvc;
using App.Entities.ViewModels.Donations;
using App.BLL.Donations;

namespace FloridoERP.Controllers.Donations
{
    public class DonationsController : Controller
    {
        private DonationsBusiness _DonationsBusiness;
        private DonationsItemBusiness _DonationsItemBusiness;

        public DonationsController()
        {
            _DonationsBusiness = new DonationsBusiness();
            _DonationsItemBusiness = new DonationsItemBusiness();
        }

        // GET: Donations
        public ActionResult DONA001()
        {
            var Model = new Donation();
            Model.DonationsList = _DonationsBusiness.GetDonationsCampaigns();
            return View(Model);
        }

        [HttpPost]
        public ActionResult DONA001(Donation Model)
        {
            if (Session["User"] != null)
            {
                if (_DonationsBusiness.AddDonationCampaign(Model))
                    return RedirectToAction("DONA001");
            }

            return View(Model);
        }        

        public ActionResult ActionGetArticles(int DonationId)
        {
            var Articles = _DonationsItemBusiness.GetItemsByDonationNumber(DonationId);
            return Json(new { success = true, Json = Articles, responseText = "Articulos de las campañas" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ActionArticles(int DonationId, bool IsFromEdit, int ArticleId)
        {
            var Model = new DonationItem();
            if (IsFromEdit)
                Model = _DonationsItemBusiness.GetArticleById(ArticleId);
            else
                Model.DonationId = DonationId;

            Model.IsFromEdit = IsFromEdit;
            ModelState.Clear();
            return PartialView("_DONA001ARTICLES", Model);
        }

        [HttpPost]
        public ActionResult ActionArticles(DonationItem Model)
        {
            if (!Model.IsFromEdit)
                if (_DonationsItemBusiness.AddArticle(Model))
                    return Json(new { success = true, Json = Model, responseText = "Articulo guardado" }, JsonRequestBehavior.AllowGet);

            if (Model.IsFromEdit)
                if (_DonationsItemBusiness.UpdateArticle(Model))
                    return Json(new { success = true, Json = Model, responseText = "Articulo editado" }, JsonRequestBehavior.AllowGet);

            return PartialView("_DONA001ARTICLES", Model);
        }

        [HttpGet]
        public ActionResult ActionCampaigns(int DonationId)
        {
            var Model = new Donation();
            Model = _DonationsBusiness.GetDonationById(DonationId);
            ModelState.Clear();
            return PartialView("_DONA001CAMPAIGNS", Model);
        }

        [HttpPost]
        public ActionResult ActionCampaigns(Donation Model)
        {
            if(_DonationsBusiness.UpdateDonationCampaigns(Model))
                return Json(new { success = true, Json = Model, responseText = "Campaña editada" }, JsonRequestBehavior.AllowGet);

            return PartialView("_DONA001CAMPAIGNS", Model);
        }

        [HttpPost]
        public ActionResult ActionDeleteCampaign(int DonationId)
        {
            if (_DonationsBusiness.DeleteCampaign(DonationId))
                return Json(new { success = true, Json = DonationId, responseText = "Campaña borrada" }, JsonRequestBehavior.AllowGet);

            return Json(new { success = false, responseText = "Ocurrió un error, contacte a sistemas!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

FloridoERP/Views/Donations/_DONA001ARTICLES.cshtml
@model App.Entities.ViewModels.Donations.DonationItem
<div class="modal fade" id="ArticlesModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                @if (Model.IsFromEdit)
                {
                    <h4 id="ModalTitle" class="modal-title">Editar Artículo</h4>
                    <small id="ModalDescription" class="font-bold">Formulario para editar un articulo.</small>
                }
                else
                {
                    <h4 id="ModalTitle" class="modal-title">Agregar Artículo</h4>
                    <small id="ModalDescription" class="font-bold">Formulario para agregar un artículo.</small>
                }
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("ActionArticles", "Donations", FormMethod.Post, new { name = "formAddEditArticles", id = "formAddEditArticles" }))
                {
                    @Html.HiddenFor(model => model.DonationId)
                    @Html.HiddenFor(model => model.IsFromEdit)
                    <div class="form-group row">
                        @if (Model.IsFromEdit)
                        {
                            <div class="col-md-4">
                                @Html.LabelFor(model => model.Article, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    @Html.HiddenFor(model => model.Article)
                                    <span class="input-group-addon"><i class="fa fa-bookmark"></i></span>
                                    @Html.EditorFor(model => model.Article, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.Article, "", new { @class = "text-danger" })
                            </div>
                        }
                        else
                        {
                            <div class="col-md-4">
                                @Html.LabelFor(model => model.Article, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">                                    
                                    <span class="input-group-addon"><i class="fa fa-bookmark"></i></span>
                                    @Html.EditorFor(model => model.Article, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.Article, "", new { @class = "text-danger" })
                            </div>
                        }
                        <div class="col-md-4">
                            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                <span class="input-group-addon"><i class="fa fa-money"></i></span>
                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                        @if (Model.IsFromEdit)
                        {
                            @Html.HiddenFor(model => model.Id)
                            <div class="col-md-4">
                                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label" })
                                <div class="col-md-10 input-group m-b">
                                    <div class="col-md-7">
                                        @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="col-md-4"></div>
                        }
                    </div>
                    <div class="row">
                        <div class="text-right">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                            <input type="button" value="Guardar" class="btn btn-success" id="SaveArticles" onclick="SaveChanges()" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

FloridoERP/Views/Donations/_DONA001CAMPAIGNS.cshtml
@model App.Entities.ViewModels.Donations.Donation

<div class="modal fade" id="CampaignsModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                <h4 id="ModalTitle" class="modal-title">Editar Campaña</h4>
                <small id="ModalDescription" class="font-bold">Formulario para editar una campaña.</small>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("ActionCampaigns", "Donations", FormMethod.Post, new { name = "formEditCampaigns", id = "formEditCampaigns" }))
                {
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group row">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.HiddenFor(model => model.Name)
                                <span class="input-group-addon"><i class="fa fa-bookmark"></i></span>
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            </div>
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Organization, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                @Html.HiddenFor(model => model.Organization)
                                <span class="input-group-addon"><i class="fa fa-group"></i></span>
                                @Html.EditorFor(model => model.Organization, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker ModalDatePicker", @id = "StartDateModal" } })
                            </div>
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10 input-group m-b">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker ModalDatePicker", @id = "EndDateModal" } })
                            </div>
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="text-right">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                            <input type="button" value="Guardar" class="btn btn-success" id="SaveCampaign" onclick="SaveChangesCampaign()" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<div id="ajaxTarget">
    <script type="text/javascript">        
        $('.ModalDatePicker').datepicker({
            autoclose: true,
            format: 'dd/mm/yyyy',
            language: 'es'
        });

        //Validate Date.
        $("#StartDateModal").on('change', function () {
            var date = stringToDate($("#StartDateModal").val());
            var endDate = stringToDate($("#EndDateModal").val());
            var currentDate = stringToDate(GetCurrentDate());

            if (endDate < date) {
                toastr.error('La fecha inicial no puede ser mayor a la fecha final.');
                $("#SaveCampaign").attr("disabled", "disabled");
                $("#StartDateModal").attr('style', 'border-color: red !important');
                return;
            }

            if (currentDate > date) {
                toastr.error('La fecha inicial no puede ser menor al día de hoy.');
                $("#SaveCampaign").attr("disabled", "disabled");
                $("#StartDateModal").attr('style', 'border-color: red !important');
                return;
            }

            $("#SaveCampaign").removeAttr("disabled");
            $("#StartDateModal").css('border-color', '');
        });

        $("#EndDateModal").on('change', function () {
            var date = stringToDate($("#EndDateModal").val());
            var startDate = stringToDate($("#StartDateModal").val());
            var currentDate = stringToDate(GetCurrentDate());

            if (startDate > date) {
                toastr.error('La fecha final no puede ser menor a la fecha inicial.');
                $("#SaveCampaign").attr("disabled", "disabled");
                $("#EndDateModal").attr('style', 'border-color: red !important');
                return;
            }

            if (currentDate > date) {
                toastr.error('La fecha final no puede ser menor al día de hoy.');
                $("#SaveCampaign").attr("disabled", "disabled");
                $("#EndDateModal").attr('style', 'border-color: red !important');
                return;
            }

            if (date == startDate) {
                toastr.error('La fecha final no puede ser igual a la fecha inicial.');
                $("#SaveCampaign").attr("disabled", "disabled");
                $("#EndDateModal").attr('style', 'border-color: red !important');
                return;
            }

            $("#SaveCampaign").removeAttr("disabled");
            $("#EndDateModal").css('border-color', '');
        });

        //Function to Get the Current Date in format dd/mm/yyyy
        function GetCurrentDate() {
            var today = new Date();
            var dd = today.getDate();
            var mm = today.getMonth() + 1; //January is 0!
            var yyyy = today.getFullYear();

            if (dd < 10) {
                dd = '0' + dd;
            }

            if (mm < 10) {
                mm = '0' + mm;
            }

            today = dd + '/' + mm + '/' + yyyy;

            return today;
        }

        //Convert strings formats dd/mm/yyyy to date
        function stringToDate(dateStr) {
            var parts = dateStr.split("/")
            return new Date(parts[2], parts[1] - 1, parts[0])
        }

    </script>
</div>