FloridoERP/ViewModels/Configuration/ConfigurationAddPages.cs
using App.Entities;
using System;
using System.Collections.Generic;

namespace FloridoERP.ViewModels.Configuration
{

    public class ConfigurationAddPages
    {

        public string page_id { get; set; }
        public string page_name { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string cuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string uuser { get; set; }
        public string program_id { get; set; }
        public virtual List<SYS_PAGE_MASTER> Page { get; set; }

        public SYS_PAGE_MASTER PAGES { get { return new SYS_PAGE_MASTER { page_id = page_id, page_name = page_name, description = description, url = url, active_flag = active_flag, cdate = cdate, cuser = cuser, udate = udate, uuser = uuser, program_id = "ADMS001.cshtml" }; } }
        public SYS_PAGE_MASTER_STORE PAGES_STORE { get { return new SYS_PAGE_MASTER_STORE { page_id = page_id, page_name = page_name, description = description, url = url, active_flag = active_flag, cdate = cdate, cuser = cuser, udate = udate, uuser = uuser, program_id = "ADMS001.cshtml" }; } }


    }
}

FloridoERP/ViewModels/Configuration/ConfigurationAddPagesUser.cs
using App.BLL.Site;
using App.Entities;
using App.Entities.ViewModels.Site;
using System.Collections.Generic;
using System.Web.Mvc;

namespace FloridoERP.ViewModels.Configuration
{
    public class ConfigurationAddPagesUser
    {
        public virtual List<MA_CODE> ListDepartment { get; set; }
        public string EmployeeNumber { get; set; }

        public string userName { get; set; }
        public string FullName { get; set; }
        public virtual List<USER_MASTER> Users { get; set; }

        private SiteBusiness _siteConfigBusiness = new SiteBusiness();
        public virtual List<SiteModel> Site { get; set; }

        public IEnumerable<SelectListItem> SiteList
        {
            get
            {
                return FillSelectListSite();
            }
        }
        public List<SelectListItem> FillSelectListSite()
        {
            Site = _siteConfigBusiness.GetAllSitesModel();
            List<SelectListItem> sites = new List<SelectListItem>();
            sites.Add(new SelectListItem { Text = "Seleccione una opción", Value = "" });
            foreach (var n in Site)
            {
                sites.Add(new SelectListItem { Text = n.SiteName, Value = n.SiteCode });
            }
            return sites;
        }
    }
}

FloridoERP/ViewModels/Configuration/ConfigurationAddRoles.cs
using App.BLL.Site;
using App.Entities;
using App.Entities.ViewModels.Site;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace FloridoERP.ViewModels.Configuration
{

    public class ConfigurationAddRoles
    {
        public string role_id { get; set; }
        public string role_name { get; set; }
        public string role_description { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string cuser { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string uuser { get; set; }
        public virtual ICollection<SYS_ROLE_MASTER> RolesCollection { get; set; }
        public SYS_ROLE_MASTER ROLES { get { return new SYS_ROLE_MASTER { role_id = role_id, role_name = role_name, role_description = role_description, active_flag = active_flag, cdate = cdate, cuser = cuser, udate = udate, uuser = uuser }; } }
        public SYS_ROLE_MASTER_STORE ROLES_STORE { get { return new SYS_ROLE_MASTER_STORE { role_id = role_id, role_name = role_name, role_description = role_description, active_flag = active_flag, cdate = cdate, cuser = cuser, udate = udate, uuser = uuser }; } }

        
    }
}

FloridoERP/Controllers/Configuration/ConfigurationController.cs
using App.BLL;
using App.BLL.Configuration;
using App.BLL.MaCode;
using App.Common;
using FloridoERP.ViewModels;
using FloridoERP.ViewModels.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloridoERP.Controllers.Configuration
{
    [Authorize]
    public class ConfigurationController : Controller
    {
        // GET: Configuration
        private readonly SysPageMasterBusiness _PageMasterRepo;
        private readonly SysRoleMasterBusiness _RoleMasterRepo;
        private readonly SysRolePageBusiness _RolePageRepo;
        private readonly UserMasterBusiness _userMasterRepo;
        private readonly SysRoleUserBusiness _RoleUserRepo;
        private readonly UserPwdBusiness _sysUserPwdBusiness;
        private readonly MaCodeBusiness _maCodeBusiness;

        public ConfigurationController()
        {
            _PageMasterRepo = new SysPageMasterBusiness();
            _RoleMasterRepo = new SysRoleMasterBusiness();
            _RolePageRepo = new SysRolePageBusiness();
            _userMasterRepo = new UserMasterBusiness();
            _RoleUserRepo = new SysRoleUserBusiness();
            _sysUserPwdBusiness = new UserPwdBusiness();
            _maCodeBusiness = new MaCodeBusiness();
        }

        public ActionResult MENADMS000()
        {
            if (Session["User"] != null)
                return View();

            return RedirectToAction("Login", "Home");
        }
        public ActionResult ADMS001()
        {
            if (Session["User"] != null)
            {
                ConfigurationAddPages model = new ConfigurationAddPages
                {
                    Page = _PageMasterRepo.GetAllPagesAdmin()
                };
                return View(model);
            }
            return RedirectToAction("Login", "Home");
        }

        public ActionResult ADMS002()
        {
            if (Session["User"] != null)
            {
                ConfigurationAddRoles model = new ConfigurationAddRoles
                {
                    RolesCollection = _RoleMasterRepo.GetAllRolesAdmin(),
                    active_flag = true
                };
                return View(model);
            }
            return RedirectToAction("Login", "Home");
        }

        public ActionResult ADMS003()
        {
            if (Session["User"] != null)
            {
                ConfigurationAddRoles model = new ConfigurationAddRoles()
                {
                    RolesCollection = _RoleMasterRepo.GetAllRolesAdmin(),
                    active_flag = true
                };
                return View(model);
            }
            return RedirectToAction("Login", "Home");
        }

        public ActionResult ADMS004()
        {
            if (Session["User"] != null)
            {
                ConfigurationAddPagesUser model = new ConfigurationAddPagesUser
                {
                    Users = _userMasterRepo.GetAllUsers(),
                    ListDepartment = _maCodeBusiness.GetListByCode("DepartmentId")
                };
                return View(model);
            }
            return RedirectToAction("Login", "Home");
        }

        public ActionResult ADMS005()
        {
            if (Session["User"] != null)
                return View();

            return RedirectToAction("Login", "Home");
        }

        public ActionResult ADMS007()
        {
            if (Session["User"] != null)
                return View();

            return RedirectToAction("Login", "Home");
        }

        //Obetenemos informacion de usuario y retornamos modelo a la vista ADMS006
        public ActionResult ADMS006()
        {
            if (Session["User"] != null)
            {
                RegisterUserMaster model = new RegisterUserMaster();
                //Busca informacion por nombre de usuario HttpContext.User.Identity.Name
                var item = _userMasterRepo.GetUserMasterByUsername(HttpContext.User.Identity.Name);
                if (item != null)
                {
                    //Asignamos Valores al ViewModel RegisterUserMaster
                    model.EmployeeNumber = item.emp_no;
                    model.Username = item.user_name;
                    model.FirstName = item.first_name;
                    model.LastName = item.last_name;
                    model.Phone = item.office_tel;
                    model.Cellphone = item.mobile_tel;
                    model.DateOfBirth = item.birth_date.Value;
                    model.Email = item.email;
                    model.photo = item.photo;
                }
                return View(model);
            }
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public ActionResult ActionUpdateUser(RegisterUserMaster model)
        {
            if (ModelState.IsValid)
            {
                if (!_userMasterRepo.IsValidEmailAddress(model.Email))
                    return Json(new { success = false, responseText = "Dominio de correo incorrecto. Ejemplo: correo@elflorido.com.mx" }, JsonRequestBehavior.AllowGet);

                var employee = _userMasterRepo.GetUserMasterByEmployeeNumber(model.EmployeeNumber);
                if (_userMasterRepo.EmployeeUsernameExists(model.Username) & employee.user_name != model.Username)
                    return Json(new { success = false, responseText = "Este nombre de usuario ya se encuentra registrado" }, JsonRequestBehavior.AllowGet);

                if (model.Password != null)
                {
                    employee.USER_PWD.password = Common.SetPassword(model.Password);
                    employee.USER_PWD.status = "A";
                    employee.USER_PWD.failed_attempts = 0;
                    employee.USER_PWD.pass_code = "";
                }
                else
                {
                    employee.user_name = Session["User"].ToString();
                    employee.first_name = model.FirstName;
                    employee.last_name = model.LastName;
                    employee.office_tel = model.Phone;
                    employee.mobile_tel = model.Cellphone;
                    employee.birth_date = model.DateOfBirth;
                    employee.email = model.Email;
                }

                if (_userMasterRepo.UpdateUserMaster(employee))
                    return Json(new { success = true, responseText = "Registro Exitoso!" }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { success = false, responseText = "Error al editar usuario" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return Json(new { success = false, responseText = allErrors.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult ActionUploadUserPhoto()
        {
            try
            {
                var EmployeeNumber = Request["EmployeeNumber"];
                var employee = _userMasterRepo.GetUserMasterByEmployeeNumber(EmployeeNumber);
                HttpPostedFileBase fs = Request.Files[0];
                BinaryReader br = new BinaryReader(Request.Files[0].InputStream);
                byte[] bytes = br.ReadBytes((Int32)fs.ContentLength);
                employee.photo = bytes;

                if (_userMasterRepo.UpdateUserMaster(employee))
                    return Json(new { success = true, responseText = "Registro Exitoso!" }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { success = false, responseText = "Error al editar usuario" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception df)
            {
                var k = df.Message;
                throw;
            }
        }

        public ActionResult ActionDeletePicture(string EmployeeNumber)
        {
            var employee = _userMasterRepo.GetUserMasterByEmployeeNumber(EmployeeNumber);

            if (_userMasterRepo.DeletePicture(employee))
                return Json(new { success = true, responseText = "Registro Exitoso!" }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { success = false, responseText = "Error al editar usuario." }, JsonRequestBehavior.AllowGet);
        }

        //inserta paginas en el sistema.
        [HttpPost]
        public ActionResult ActionInsertPages(ConfigurationAddPages AddPages,bool type)
        {
            if (Session["User"] != null)
            {
                AddPages.cuser = Session["User"].ToString();
                AddPages.cdate = DateTime.Now;
                AddPages.active_flag = true;
                if (ModelState.IsValid)
                {
                    var page = (dynamic)null;
                    if (type)//Paginas de tienda
                    {
                        page = _PageMasterRepo.SearchPageStore(AddPages.page_id);
                    }
                    else // Paginas Global
                    {
                        page = _PageMasterRepo.SearchPage(AddPages.page_id);
                    }
                    if (page == null)
                    {
                        var retu = (dynamic)null;
                        if (type)//Paginas de tienda
                        {
                            retu = _PageMasterRepo.AddPagesMasterStore(AddPages.PAGES_STORE);
                        }
                        else // Paginas Global
                        {
                            retu = _PageMasterRepo.AddPagesMaster(AddPages.PAGES);
                        }
                        if (retu)
                        {
                            List<ConfigurationAddPages> CostumModel = new List<ConfigurationAddPages>();

FloridoERP/Views/Configuration/ADMS001.cshtml
@model FloridoERP.ViewModels.Configuration.ConfigurationAddPages
@{ ViewBag.Title = "ADMS001"; }
@section Styles { @Styles.Render("~/bundles/simple_toggle/css") }
<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="MENADMS000">Configuración</a></li>
                    <li>
                        <a href="ADMS007">Administración de Roles y Permisos</a>
                    </li>
                    <li class="active">
                        <span>Páginas</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Administración de páginas
            </h2>
            <small>Inserción y modificación de paginas. </small>
        </div>
    </div>
</div>
<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        <a class="closebox"><i class="fa fa-times"></i></a>
                    </div>
                    Paginas
                </div>
                <div class="panel-body">   
                    <div class="row">
                        <div class="col-lg-5">
                            <h4 id="labelCreditor" class="text-success pull-right">Global</h4>
                        </div>
                        <div class="col-lg-1">
                            <label class="switch">
                                <input id="checkView" type="checkbox" onclick="ChangeValues(this);">
                                <span class="slider round"></span>
                            </label>
                        </div>
                        <div class="col-lg-5 pull-left">
                            <h4 id="labelSite" class="pull-left">Tienda</h4>
                        </div>
                    </div>
                        <div class="table-responsive">
                            <table id="TablePages" class="table table-striped table-bordered table-hover" style="width:100%">
                                <thead>
                                    <tr>
                                        <th><button type="button" class="btn btn-xs btn-success " onclick="AddPage();"><i class="fa fa-plus"></i> Agregar</button></th>
                                        <th>Página Id</th>
                                        <th>Nombre</th>
                                        <th>Descripcion</th>
                                        <th>Url</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Page)
                                    {
                                        <tr>
                                            <td></td>
                                            <td>@item.page_id.ToString()</td>
                                            <td>@item.page_name.ToString()</td>
                                            <td>@item.description.ToString()</td>
                                            <td>@item.url</td>
                                            <td class="loadStyle">@item.active_flag.Value</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ModalAddPages" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                <h4 id="ModalTitle" class="modal-title">Agregar Pagina</h4>
                <small id="ModalDescription" class="font-bold">Formulario para registrar una nueva pagina.</small>
            </div>
            @using (Html.BeginForm("ActionInsertPages", "Configuration", FormMethod.Post, new { name = "form", id = "form" }))
            {
                <div class="modal-body">

                    <div class="row">
                        <div class="form-group col-lg-6">
                            <label for="page_id" title="ID Pagina." data-toggle="tooltip" data-placement="right">ID Pagina</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-key"></span>
                                </span>
                                @Html.TextBoxFor((x => x.page_id), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label for="page_name" title="Nombre de la página." data-toggle="tooltip" data-placement="right">Nombre de Pagina</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-file-text-o"></span>
                                </span>
                                @Html.TextBoxFor((x => x.page_name), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label title="description" data-toggle="Descripción de la página." data-placement="right">Descripción</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-file-text"></span>
                                </span>
                                @Html.TextBoxFor((x => x.description), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label title="URL de la página" data-toggle="tooltip" data-placement="right">URL</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-link"></span>
                                </span>
                                @Html.TextBoxFor((x => x.url), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label title="Status" data-toggle="tooltip" data-placement="right">Activo/Inactivo</label>
                            <div id="Check" class="i-checks">@Html.CheckBoxFor((x => x.active_flag.HasValue), new { @class = "form-control" })</div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Cancelar</button>
                    <button class="btn btn-primary"><i class="fa fa-check"></i> Guardar Cambios</button>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts { @Scripts.Render("~/bundles/ADMS001/js") }

FloridoERP/Views/Configuration/ADMS002.cshtml
@model FloridoERP.ViewModels.Configuration.ConfigurationAddRoles
@{ ViewBag.Title = "ADMS002"; }
@section Styles { @Styles.Render("~/bundles/simple_toggle/css") }
<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i id="fa" class="fa fa-arrow-up"></i>
                </div>
            </a>
            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="MENADMS000">Configuración</a></li>
                    <li>
                        <a href="ADMS007">Administración de Roles y Permisos</a>
                    </li>
                    <li class="active">
                        <span>Roles</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Roles del sistema
            </h2>
            <small>Inserción y modificación de roles.</small>
        </div>
    </div>
</div>
<div class="content animate-panel">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                        <a class="closebox"><i class="fa fa-times"></i></a>
                    </div>
                    Paginas
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-5">
                            <h4 id="labelCreditor" class="text-success pull-right">Global</h4>
                        </div>
                        <div class="col-lg-1">
                            <label class="switch">
                                <input id="checkView" type="checkbox" onclick="ChangeValues(this);">
                                <span class="slider round"></span>
                            </label>
                        </div>
                        <div class="col-lg-5 pull-left">
                            <h4 id="labelSite" class="pull-left">Tienda</h4>
                        </div>
                    </div>
                    <table id="TableRoles" class="table table-striped table-bordered table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th><button type="button" class="btn btn-xs btn-success " onclick="AddRole();"><i class="fa fa-plus"></i>  Agregar</button></th>
                                <th>Role Id</th>
                                <th>Nombre</th>
                                <th>Descripcion</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.RolesCollection)
                            {
                                <tr>
                                    <td></td>
                                    <td>@item.role_id.ToString()</td>
                                    <td>@item.role_name.ToString()</td>
                                    <td>@item.role_description.ToString()</td>
                                    <td class="loadStyle">@item.active_flag</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="ModalAddPages" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="color-line"></div>
            <div class="modal-header">
                <h4 id="ModalTitle" class="modal-title">Agregar Pagina</h4>
                <small id="ModalDescription" class="font-bold">Formulario para registrar una nueva pagina.</small>
            </div>
            @using (Html.BeginForm("ActionInsertRoles", "Configuration", FormMethod.Post, new { name = "form", id = "form" }))
            {
                <div class="modal-body">

                    <div class="row">
                        <div class="form-group col-lg-6">
                            <label for="page_id" title="ID Pagina." data-toggle="tooltip" data-placement="right">ID Rol</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-key"></span>
                                </span>
                                @Html.TextBoxFor((x => x.role_id), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label for="page_name" title="Nombre de la página." data-toggle="tooltip" data-placement="right">Nombre de Rol</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-file-text-o"></span>
                                </span>
                                @Html.TextBoxFor((x => x.role_name), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label title="description" data-toggle="Descripción de la página." data-placement="right">Descripción</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="fa fa-file-text"></span>
                                </span>
                                @Html.TextBoxFor((x => x.role_description), new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group col-lg-6">
                            <label title="Status" data-toggle="tooltip" data-placement="right">Activo/Inactivo</label>
                            <div id="Check" class="i-checks">@Html.CheckBoxFor((x => x.active_flag.Value), new { @class = "form-control" })</div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> Cancelar</button>
                    <button class="btn btn-primary"><i class="fa fa-check"></i>  Guardar Cambios</button>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts { @Scripts.Render("~/bundles/ADMS002/js") }

FloridoERP/Views/Configuration/ADMS005.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="content animate-panel">
    <div class="row">
        <div class="col-md-3">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="ADMS006">
                            <h2 class="m-b-xs">Editar Perfil.</h2>
                            <div class="m">
                                <i class="pe-7s-id fa-5x"></i>
                            </div>
                            <p class="small">
                                Editar Información personal de usuario.
                            </p>
                            <br />
                        </a>
                        <a href="ADMS006" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FloridoERP/Views/Configuration/MENADMS000.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="content animate-panel">
    <div class="row menu-row">
        <div class="col-xs-12 col-md-3">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="ADMS006">
                            <h2 class="m-b-xs">Editar Perfil <br/><br/></h2>
                            <div class="m">
                                <i class="pe-7s-id fa-5x"></i>
                            </div>
                            <p class="small">
                                Editar Información personal de usuario.<br /><br />
                            </p>
                            <br />
                        </a>
                        <a href="ADMS006" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="hpanel contact-panel">
                <div class="panel-body">
                    <div class="text-center">
                        <a href="ADMS001">
                            <h2 class="m-b-xs">Administración de páginas.</h2>
                            <div class="m">
                                <i class="pe-7s-browser fa-5x"></i>
                            </div>
                            <p class="small">
                                Configuración de páginas en el sistema.<br /><br />
                            </p>
                            <br/>
                        </a>
                        <a href="ADMS007" class="btn btn-success btn-sm">Ir a la página</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>